apiVersion: v1
kind: Namespace
metadata:
  name: vue-user
  labels:
    istio-injection: enabled
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: user-imroc-io
  namespace: vue-user
spec:
  secretName: vue-user-imroc-io-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - vue.user.k8s.show
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: app-sc
  namespace: vue-user
reclaimPolicy: Retain
volumeBindingMode: Immediate
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vue-user-app-p-volume
  namespace: vue-user
  labels:
    type: app
spec:
  storageClassName: app-sc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /apps
    server: localhost.kvm-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc-claim
  namespace: vue-user
spec:
  storageClassName: app-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vue-user
  name: vue-user
  namespace: vue-user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vue-user
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: vue-user
    spec:
      containers:
      - args: ["/sh/init_openresty.sh"]
        env:
        - name: SERVICE_NAME
          value: vue-user
        - name: SERVICE_TAGS
          value: vue-user,http,80
        image: xjyplayer/simple_user_nginx:1.0.2
        imagePullPolicy: IfNotPresent
        name: user-nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /apps/vue-user_pro
          subPath: vue-user_pro
          name: vue-user-pvc
        - mountPath: /apps/logs
          subPath: logs
          name: vue-user-pvc
        - mountPath: /apps/simple-user-nginx
          subPath: simple-user-nginx
          name: vue-user-pvc
        - mountPath: /usr/local/openresty/nginx/conf/nginx_template.conf
          subPath: conf/nginx/nginx.conf
          name: nginx-conf
        workingDir: /apps/simple-user-nginx
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: vue-user-pvc
        persistentVolumeClaim:
          claimName: app-pvc-claim
      - name: nginx-conf
        configMap:
          name: vue-user-nginx-config-map
          items:
          - key: nginx.conf
            path: conf/nginx/nginx.conf
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: vue-user
  name: vue-user-server
  namespace: vue-user
spec:
  ports:
  - name: vue-user-server-main-port
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: vue-user
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name:  user-gw
  namespace: vue-user
  labels:
    app: user
    io.kompose.service: user
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - vue.user.k8s.show
      tls:
        mode: SIMPLE
        credentialName: vue-user-imroc-io-tls
      port:
        number: 443
        name: vue-user-dashboard-https
        protocol: HTTPS
    - hosts:
        - vue.user.k8s.show
      port:
        number: 80
        name: vue-user-dashboard-http
        protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: user-dr
  namespace: vue-user
spec:
  host: user.user.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user-vs
  namespace: vue-user
spec:
  hosts:
    - vue.user.k8s.show
  gateways:
    - user-gw
  http:
    - match: null
      route:
        - destination:
            host: "user.user.svc.cluster.local"
            port:
              number: 80

